site_name: Rhexis
site_url: https://rhexis.io
repo_name: Rhexis/Rhexis.github.io
repo_url: https://github.com/Rhexis/Rhexis.github.io
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: light green
  icon:
    repo: fontawesome/brands/github
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight